<?php
/**
 * Admin Controller
 *
 * Registers the WooCommerce submenu page, enqueues the React admin app,
 * and localizes REST data for the frontend.
 *
 * @package WooUpsellPro\Admin
 */

namespace WooUpsellPro\Admin;

if (! defined('ABSPATH')) {
    exit;
}

/**
 * WUP_Admin
 *
 * Handles WordPress admin integration: menu, assets, and page render.
 */
class WUP_Admin {

    /** @var string Admin page hook suffix returned by add_submenu_page(). */
    private string $page_hook = '';

    /**
     * Register hooks via loader.
     *
     * @param object $loader WUP_Loader instance.
     */
    public function register_hooks(object $loader): void {
        $loader->add_action('admin_menu', $this, 'add_admin_menu');
        $loader->add_action('admin_enqueue_scripts', $this, 'enqueue_admin_assets');
    }

    /**
     * Add submenu page under WooCommerce menu.
     */
    public function add_admin_menu(): void {
        $this->page_hook = add_submenu_page(
            'woocommerce',
            __('Upsell Pro', 'woo-upsell-pro'),
            __('Upsell Pro', 'woo-upsell-pro'),
            'manage_woocommerce',
            'wup-campaigns',
            [$this, 'render_admin_page']
        );
    }

    /**
     * Enqueue React app assets — only on our admin page.
     *
     * @param string $hook Current admin page hook suffix.
     */
    public function enqueue_admin_assets(string $hook): void {
        if ($hook !== $this->page_hook) {
            return;
        }

        $build_dir = WUP_PLUGIN_DIR . 'admin/build/';
        $build_url = WUP_PLUGIN_URL . 'admin/build/';

        // Load asset manifest generated by @wordpress/scripts if available.
        $asset_file = $build_dir . 'index.asset.php';
        $asset      = file_exists($asset_file)
            ? require $asset_file
            : ['dependencies' => ['wp-element', 'wp-components', 'wp-api-fetch', 'wp-i18n'], 'version' => WUP_VERSION];

        wp_enqueue_script(
            'wup-admin',
            $build_url . 'index.js',
            $asset['dependencies'],
            $asset['version'],
            true
        );

        if (file_exists($build_dir . 'index.css')) {
            wp_enqueue_style(
                'wup-admin',
                $build_url . 'index.css',
                ['wp-components'],
                $asset['version']
            );
        }

        // Also enqueue WP components styles.
        wp_enqueue_style('wp-components');

        // Localize data for the React app.
        wp_localize_script('wup-admin', 'wupAdmin', [
            'rest_url'  => esc_url_raw(rest_url('wup/v1')),
            'nonce'     => wp_create_nonce('wp_rest'),
            'settings'  => get_option('wup_settings', []),
            'site_url'  => get_site_url(),
            'admin_url' => admin_url(),
        ]);

        // Tell @wordpress/api-fetch to use our nonce.
        wp_add_inline_script(
            'wup-admin',
            'wp.apiFetch.use( wp.apiFetch.createNonceMiddleware( wupAdmin.nonce ) );',
            'before'
        );
    }

    /**
     * Render the admin page — React app mounts here.
     */
    public function render_admin_page(): void {
        if (! current_user_can('manage_woocommerce')) {
            wp_die(esc_html__('You do not have permission to access this page.', 'woo-upsell-pro'));
        }
        echo '<div class="wrap"><div id="wup-admin-root"></div></div>';
    }
}
